package es.udc.muei.riws.routeprofile.util;

public enum FieldsEnum {
	url, PR_DISTANCE, PR_LOOP, PR_ELEVATION_GAIN_UP_HILL, PR_ELEVATION_MAX, PR_ELEVATION_GAIN_DOWN_HILL, PR_ELEVATION_MIN, PR_LATITUDE, PR_LONGITUDE
}